controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: false

    omnidirectional_controller:
      type: omnidirectional_controllers/OmnidirectionalController
      

omnidirectional_controller:
  ros__parameters:
    wheel_names:
      - joint_wheel_roueholonome3 # motor on the x axis of the robot
      - joint_wheel_roueholonome1
      - joint_wheel_roueholonome2 # motor on the y axis side of the robot
      
    robot_radius: 0.144 # robot center to the outer edge center of the wheel
    wheel_radius: 0.058
    gamma: 30.0 # angle between body fixed y axis and the normal of third wheel in list above

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    odom_numeric_integration_method: runge_kutta2

    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    use_stamped_vel: false