controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: True

    omnidirectional_controller:
      type: omnidirectional_controllers/OmnidirectionalController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["Rouleau_a_roueholonome1","Rouleau_b_roueholonome1","Rouleau_c_roueholonome1","Rouleau_d_roueholonome1","Rouleau_e_roueholonome1","Rouleau_f_roueholonome1","Rouleau_g_roueholonome1","Rouleau_h_roueholonome1","Rouleau_i_roueholonome1","Rouleau_j_roueholonome1",
                  "Rouleau_a_roueholonome2","Rouleau_b_roueholonome2","Rouleau_c_roueholonome2","Rouleau_d_roueholonome2","Rouleau_e_roueholonome2","Rouleau_f_roueholonome2","Rouleau_g_roueholonome2","Rouleau_h_roueholonome2","Rouleau_i_roueholonome2","Rouleau_j_roueholonome2",
                  "Rouleau_a_roueholonome3","Rouleau_b_roueholonome3","Rouleau_c_roueholonome3","Rouleau_d_roueholonome3","Rouleau_e_roueholonome3","Rouleau_f_roueholonome3","Rouleau_g_roueholonome3","Rouleau_h_roueholonome3","Rouleau_i_roueholonome3","Rouleau_j_roueholonome3",]

omnidirectional_controller:
  ros__parameters:
    wheel_names:
      - joint_wheel_roueholonome3
      - joint_wheel_roueholonome2
      - joint_wheel_roueholonome1
      
    robot_radius: 0.2
    wheel_radius: 0.058
    gamma: 30.0 # angle between body fixed y axis and the normal of third wheel in list above

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    odom_numeric_integration_method: runge_kutta2

    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    use_stamped_vel: false