teleop_twist_joy_node:
  ros__parameters:
   
    axis_linear:
      x: 4
      y: 3
    scale_linear:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: -2.0

    enable_button: 1
    require_enable_button: false

    enable_turbo_button: 5
    scale_linear_turbo.x: 1.0
    scale_linear_turbo.y: 1.0
    scale_angular_turbo.yaw: -4.0
